version: '3.8'

services:
  obelisk-api: #Backend Server
    build: ./server
    container_name: api
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@postgres-db:${DB_PORT}/obelisk
      - JWT_SECRET=${JWT_SECRET} # Strong key
      - NODE_ENV=production
      - SERVER_PORT=${SERVER_PORT}
      - SALT_ROUNDS=${SALT_ROUNDS}
    ports:
      - "3001:3001" # Expose API to frontend or external access
    depends_on:
      - postgres-db
    networks:
      - obelisk-network
    # hot-relaod during development
    volumes:
      - ./server:/app

  # 2. DATABASE PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_DB: obelisk           # DB Name
      POSTGRES_USER: postgres        # admin user (default)
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}  # .env or default password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pgInit:/docker-entrypoint-initdb.d/
    networks:
      - obelisk-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  obelisk-web-build: #Frontend
    build: ./client
    container_name: ui
    ports:
      - "5173:5173" # Vite dev port
    networks:
      - obelisk-network

networks:
  obelisk-network:
    driver: bridge

volumes:
  postgres-data: # PostgreSQL data persistence